/bluerov2/search_pattern:
  ros__parameters:
    enable: True
    x_min: 1.5
    x_max: 7.5
    y_min: 1.0
    y_max: 7.0
    spacing: 1.5
    input_topic: "aruco_odom"
    output_yaw_topic: "desired_yaw"
    output_surge_topic: "searching/surge_force"
    rate: 10.0
    surge_force: 10.0 
    switching_th: 0.5
    yaw_offset: 3.1415
    stonefish: false
    invert_surge: True
    desired_depth: 2.5
    depth_status_topic: "controller/depth_status"
    depth_topic: "desired_depth"


/bluerov2/box_approaching:
  ros__parameters:
    enable: True
    input_topic: "/bluerov/navigator/odometry"
    output_yaw_topic: "desired_yaw"
    output_surge_topic: "searching/surge_force"
    rate: 10.0
    surge_force: 10.0 
    switching_th: 0.5
    yaw_offset: 3.1415
    stonefish: True
    invert_surge: True
    desired_depth: 4.0
    depth_status_topic: "controller/depth_status"
    depth_topic: "desired_depth"
    area_redius: 1.0
