# YOLOv11 Detection Configuration

# Model confidence threshold (0.0 - 1.0)
# Lower values detect more objects but with more false positives
confidence: 0.5
handle_confidence: 0.5

#handle detection
handle_detection: true

#camera window
show_camera_window: true

# IOU threshold for NMS (Non-Maximum Suppression)
# Controls how much overlap is allowed between detections
threshold: 0.45

# Camera resolution (width, height)
camera_resolution:
  width: 1920
  height: 1080

# Model settings
model:
  # Path to model weights (relative to script directory)
  # weights_path: "weights/best_pb.pt"
  weights_path: "weights/alx_dec11.pt"
  # weights_path: "weights/dec5.pt"
  # Device: "cpu" or "0" (for GPU)
  device: 0
 