bluerov2:
  ekf_filter_node:
    ros__parameters:

      frequency: 5.0
      sensor_timeout: 1.0


      # ----- Frames -----
      odom_frame: "odom"
      base_link_frame: "base_link"
      world_frame: "ned"
      map_frame: "ned"
      two_d_mode: false

      publish_tf: true


      # -----------------------------
      #  INPUT 1: CAMERA ODOMETRY
      # -----------------------------
      pose0: "aruco_odom"
      pose0_config: [
        true,  true,  true,
        true,  true,  true,
        false, false, false,
        false, false, false
      ]
      pose0_differential: false
      pose0_relative: false
      pose0_pose_rejection_threshold: 3.0
      pose0_twist_rejection_threshold: 3.0

      # -----------------------------
      #  INPUT 2: IMU
      # -----------------------------
      imu0: "imu/data_republished"
      imu0_config: [
        false, false, false,
        false,  false,  true,
        false, false, false,
        false,  false,  false
      ]
      imu0_differential: false
      imu0_relative: false
      imu0_remove_gravitational_acceleration: true
      imu0_pose_rejection_threshold: 3.0
      imu0_twist_rejection_threshold: 3.0
      imu0_linear_acceleration_rejection_threshold: 3.0
      # imu0_reliability: best_effort

      # -----------------------------
      # INPUT 3: DEPTH ODOMETRY
      # -----------------------------
      pose1: "depth_odom"
      pose1_config: [
        false, false, true,
        false, false, false,
        false, false, false,
        false, false, false
      ]
      pose1_pose_rejection_threshold: 3.0
      pose1_differential: false
      pose1_relative: false
      # -----------------------------
      # INPUT 4: DEAD RECKONING ODOMETRY
      # -----------------------------
      odom0: "dead_reckoning_odom"
      odom0_config: [
        true,  true,  false,   # x, y, z
        false, false, false,    # roll, pitch, yaw
        false, false, false,   # vx, vy, vz
        false,  false,  false     # wx, wy, wz
      ]
      odom0_differential: false
      odom0_relative: true
      odom0_pose_rejection_threshold: 1.0
      odom0_twist_rejection_threshold: 3.0

      # -----------------------------
      # OUTPUT
      # -----------------------------
      print_diagnostics: true
      debug: true
